image: node:20.12.0

definitions:
  caches:
    node-modules:
      key:
        files:
          - contentful-tools/package.json
      path: node_modules

  steps:
    - step: &run-migrations
        name: Run all migrations
        caches:
          - node-modules
        script:
          - cd contentful-tools
          - npm install
          - npm run run-migrations
pipelines:
  branches:
    contentful-environment/**:
      - step: *run-migrations
  custom:
    run-migrations:
      - step: *run-migrations
